// pages/privacy.vue
<template>
  <div class="privacy-page">
    <div class="page-header">
      <h1>Privacy Policy</h1>
      <p class="subtitle">Last Updated: January 2025</p>
    </div>

    <div class="content-container">
      <div class="policy-content">
        <section class="policy-section">
          <h2>1. Introduction</h2>
          <p>Welcome to Cloudless.gr ("we," "our," or "us"). We are committed to protecting your privacy and ensuring the security of your personal information. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our AI development platform and services.</p>
        </section>

        <section class="policy-section">
          <h2>2. Information We Collect</h2>
          
          <h3>2.1 Personal Information</h3>
          <p>We collect the following personal information when you use our services:</p>
          <ul>
            <li><strong>Account Information</strong>: Email address, full name, username, and password</li>
            <li><strong>Profile Information</strong>: Avatar URL, bio, location, website, and role</li>
            <li><strong>Contact Information</strong>: Email address for communications and support</li>
            <li><strong>Authentication Data</strong>: Login credentials and session information</li>
          </ul>

          <h3>2.2 Usage Information</h3>
          <p>We automatically collect certain information about your use of our platform:</p>
          <ul>
            <li><strong>Session Data</strong>: Login/logout times, session duration, and activity timestamps</li>
            <li><strong>Device Information</strong>: IP address, user agent, device type, and browser information</li>
            <li><strong>Usage Analytics</strong>: Pages visited, features used, and interaction patterns</li>
            <li><strong>Performance Data</strong>: API request logs, error logs, and system performance metrics</li>
          </ul>

          <h3>2.3 AI Development Data</h3>
          <p>As an AI development platform, we collect:</p>
          <ul>
            <li><strong>Bot Configurations</strong>: Bot names, prompts, models, and settings</li>
            <li><strong>Model Training Data</strong>: Training parameters, datasets, and model configurations</li>
            <li><strong>Pipeline Configurations</strong>: Pipeline steps, configurations, and execution logs</li>
            <li><strong>Project Data</strong>: Project names, descriptions, and collaboration settings</li>
          </ul>

          <h3>2.4 Technical Information</h3>
          <p>We collect technical information to improve our services:</p>
          <ul>
            <li><strong>System Logs</strong>: Error logs, performance metrics, and debugging information</li>
            <li><strong>API Usage</strong>: Request patterns, response times, and usage statistics</li>
            <li><strong>Security Data</strong>: Failed login attempts, security events, and audit logs</li>
          </ul>
        </section>

        <section class="policy-section">
          <h2>3. How We Use Your Information</h2>
          
          <h3>3.1 Service Provision</h3>
          <p>We use your information to:</p>
          <ul>
            <li>Provide and maintain our AI development platform</li>
            <li>Process your account registration and authentication</li>
            <li>Enable bot creation, model training, and pipeline execution</li>
            <li>Facilitate team collaboration and project management</li>
            <li>Deliver customer support and technical assistance</li>
          </ul>

          <h3>3.2 Platform Improvement</h3>
          <p>We use aggregated data to:</p>
          <ul>
            <li>Analyze usage patterns and optimize platform performance</li>
            <li>Develop new features and improve existing functionality</li>
            <li>Identify and resolve technical issues</li>
            <li>Enhance user experience and interface design</li>
          </ul>

          <h3>3.3 Communication</h3>
          <p>We may use your contact information to:</p>
          <ul>
            <li>Send important service updates and notifications</li>
            <li>Provide customer support and respond to inquiries</li>
            <li>Share platform updates and new feature announcements</li>
            <li>Send security alerts and account-related communications</li>
          </ul>

          <h3>3.4 Security and Compliance</h3>
          <p>We use your information to:</p>
          <ul>
            <li>Protect against fraud, abuse, and security threats</li>
            <li>Ensure compliance with our Terms of Service</li>
            <li>Maintain platform security and integrity</li>
            <li>Conduct security audits and investigations</li>
          </ul>
        </section>

        <section class="policy-section">
          <h2>4. Information Sharing and Disclosure</h2>
          
          <h3>4.1 Service Providers</h3>
          <p>We may share your information with trusted third-party service providers who assist us in:</p>
          <ul>
            <li>Hosting and infrastructure services (Supabase)</li>
            <li>Analytics and performance monitoring</li>
            <li>Customer support and communication tools</li>
            <li>Security and fraud prevention services</li>
          </ul>

          <h3>4.2 Legal Requirements</h3>
          <p>We may disclose your information when required by law or to:</p>
          <ul>
            <li>Comply with legal obligations and court orders</li>
            <li>Protect our rights, property, or safety</li>
            <li>Investigate potential violations of our Terms of Service</li>
            <li>Respond to government requests and legal proceedings</li>
          </ul>

          <h3>4.3 Business Transfers</h3>
          <p>In the event of a merger, acquisition, or sale of assets, your information may be transferred as part of the business transaction, subject to the same privacy protections.</p>

          <h3>4.4 With Your Consent</h3>
          <p>We will share your information with third parties only with your explicit consent, except as described in this policy.</p>
        </section>

        <section class="policy-section">
          <h2>5. Data Storage and Security</h2>
          
          <h3>5.1 Data Storage</h3>
          <p>Your information is stored securely using:</p>
          <ul>
            <li><strong>Supabase</strong>: Cloud database and authentication services</li>
            <li><strong>Encryption</strong>: Industry-standard encryption for data in transit and at rest</li>
            <li><strong>Access Controls</strong>: Role-based access controls and authentication</li>
            <li><strong>Backup Systems</strong>: Regular data backups and disaster recovery procedures</li>
          </ul>

          <h3>5.2 Security Measures</h3>
          <p>We implement comprehensive security measures including:</p>
          <ul>
            <li><strong>Authentication</strong>: Multi-factor authentication and secure login procedures</li>
            <li><strong>Session Management</strong>: Secure session tokens and automatic logout</li>
            <li><strong>Audit Logging</strong>: Comprehensive audit trails for all data access</li>
            <li><strong>Regular Security Updates</strong>: Ongoing security monitoring and updates</li>
          </ul>

          <h3>5.3 Data Retention</h3>
          <p>We retain your information for as long as necessary to:</p>
          <ul>
            <li>Provide our services and maintain your account</li>
            <li>Comply with legal obligations</li>
            <li>Resolve disputes and enforce agreements</li>
            <li>Improve our services and platform</li>
          </ul>
        </section>

        <section class="policy-section">
          <h2>6. Your Rights and Choices</h2>
          
          <h3>6.1 Access and Control</h3>
          <p>You have the right to:</p>
          <ul>
            <li>Access and review your personal information</li>
            <li>Update and correct your account information</li>
            <li>Delete your account and associated data</li>
            <li>Export your data in a portable format</li>
            <li>Opt-out of certain communications</li>
          </ul>

          <h3>6.2 Data Portability</h3>
          <p>You can request a copy of your data, including:</p>
          <ul>
            <li>Account information and profile data</li>
            <li>Bot configurations and training data</li>
            <li>Pipeline configurations and execution logs</li>
            <li>Project data and collaboration information</li>
          </ul>

          <h3>6.3 Account Deletion</h3>
          <p>You may delete your account at any time. Upon deletion, we will:</p>
          <ul>
            <li>Remove your personal information from our systems</li>
            <li>Delete your AI models, bots, and pipelines</li>
            <li>Cancel any active subscriptions</li>
            <li>Retain certain information as required by law</li>
          </ul>
        </section>

        <section class="policy-section">
          <h2>7. Cookies and Tracking Technologies</h2>
          
          <h3>7.1 Cookies</h3>
          <p>We use cookies and similar technologies to:</p>
          <ul>
            <li>Maintain your login session and preferences</li>
            <li>Analyze platform usage and performance</li>
            <li>Provide personalized content and features</li>
            <li>Improve security and prevent fraud</li>
          </ul>

          <h3>7.2 Local Storage</h3>
          <p>We use browser local storage to:</p>
          <ul>
            <li>Store user preferences and settings</li>
            <li>Cache frequently accessed data</li>
            <li>Improve application performance</li>
            <li>Maintain form data during multi-step processes</li>
          </ul>

          <h3>7.3 Analytics</h3>
          <p>We use analytics tools to:</p>
          <ul>
            <li>Understand how users interact with our platform</li>
            <li>Identify areas for improvement</li>
            <li>Measure feature adoption and usage</li>
            <li>Optimize performance and user experience</li>
          </ul>
        </section>

        <section class="policy-section">
          <h2>8. Third-Party Services</h2>
          
          <h3>8.1 Supabase Integration</h3>
          <p>Our platform uses Supabase for:</p>
          <ul>
            <li>User authentication and account management</li>
            <li>Database storage and data management</li>
            <li>Real-time features and collaboration</li>
            <li>File storage and media management</li>
          </ul>

          <h3>8.2 External APIs</h3>
          <p>We may integrate with third-party APIs for:</p>
          <ul>
            <li>AI model training and inference</li>
            <li>Payment processing and billing</li>
            <li>Communication and notification services</li>
            <li>Analytics and monitoring tools</li>
          </ul>
        </section>

        <section class="policy-section">
          <h2>9. International Data Transfers</h2>
          <p>Your information may be transferred to and processed in countries other than your own. We ensure appropriate safeguards are in place to protect your data in accordance with applicable data protection laws.</p>
        </section>

        <section class="policy-section">
          <h2>10. Children's Privacy</h2>
          <p>Our services are not intended for children under the age of 13. We do not knowingly collect personal information from children under 13. If you believe we have collected information from a child under 13, please contact us immediately.</p>
        </section>

        <section class="policy-section">
          <h2>11. Changes to This Privacy Policy</h2>
          <p>We may update this Privacy Policy from time to time. We will notify you of any material changes by:</p>
          <ul>
            <li>Posting the updated policy on our website</li>
            <li>Sending email notifications to registered users</li>
            <li>Displaying prominent notices on our platform</li>
          </ul>
        </section>

        <section class="policy-section">
          <h2>12. Contact Information</h2>
          <p>If you have any questions about this Privacy Policy or our data practices, please contact us:</p>
          <div class="contact-info">
            <p><strong>Email:</strong> privacy@cloudless.gr</p>
            <p><strong>Address:</strong> [Your Business Address]</p>
            <p><strong>Website:</strong> https://cloudless.gr</p>
          </div>
        </section>

        <section class="policy-section">
          <h2>13. Data Protection Officer</h2>
          <p>For EU residents, you may contact our Data Protection Officer at:</p>
          <p><strong>Email:</strong> dpo@cloudless.gr</p>
        </section>

        <section class="policy-section">
          <h2>14. Complaints</h2>
          <p>If you believe we have not addressed your privacy concerns adequately, you may:</p>
          <ul>
            <li>Contact us directly to resolve the issue</li>
            <li>File a complaint with your local data protection authority</li>
            <li>Seek legal remedies as provided by applicable law</li>
          </ul>
        </section>

        <section class="policy-section">
          <h2>15. California Privacy Rights</h2>
          <p>California residents have additional rights under the California Consumer Privacy Act (CCPA):</p>
          <ul>
            <li>Right to know what personal information is collected</li>
            <li>Right to delete personal information</li>
            <li>Right to opt-out of the sale of personal information</li>
            <li>Right to non-discrimination for exercising privacy rights</li>
          </ul>
        </section>

        <section class="policy-section">
          <h2>16. GDPR Compliance</h2>
          <p>For EU residents, we comply with the General Data Protection Regulation (GDPR):</p>
          <ul>
            <li>Lawful basis for processing personal data</li>
            <li>Data subject rights and freedoms</li>
            <li>Data protection by design and default</li>
            <li>Breach notification requirements</li>
          </ul>
        </section>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
// No additional script needed for this static page
</script>

<style scoped>
.privacy-page {
  max-width: 1200px;
  margin: 0 auto;
  padding: 2rem;
}

.page-header {
  text-align: center;
  margin-bottom: 3rem;
}

.page-header h1 {
  font-size: 2.5rem;
  font-weight: 700;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
  margin-bottom: 1rem;
}

.subtitle {
  font-size: 1.1rem;
  color: rgba(0, 0, 0, 0.7);
  margin: 0;
}

.content-container {
  background: rgba(255, 255, 255, 0.8);
  backdrop-filter: blur(10px);
  border: 1px solid rgba(255, 255, 255, 0.2);
  border-radius: 20px;
  padding: 3rem;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
}

.policy-content {
  max-width: 800px;
  margin: 0 auto;
}

.policy-section {
  margin-bottom: 3rem;
}

.policy-section:last-child {
  margin-bottom: 0;
}

.policy-section h2 {
  font-size: 1.5rem;
  font-weight: 600;
  color: rgba(0, 0, 0, 0.9);
  margin-bottom: 1rem;
  padding-bottom: 0.5rem;
  border-bottom: 2px solid rgba(102, 126, 234, 0.2);
}

.policy-section h3 {
  font-size: 1.2rem;
  font-weight: 600;
  color: rgba(0, 0, 0, 0.8);
  margin: 1.5rem 0 0.75rem 0;
}

.policy-section p {
  color: rgba(0, 0, 0, 0.7);
  line-height: 1.7;
  margin-bottom: 1rem;
}

.policy-section ul {
  color: rgba(0, 0, 0, 0.7);
  line-height: 1.6;
  margin-bottom: 1rem;
  padding-left: 1.5rem;
}

.policy-section li {
  margin-bottom: 0.5rem;
}

.policy-section strong {
  color: rgba(0, 0, 0, 0.9);
  font-weight: 600;
}

.contact-info {
  background: rgba(102, 126, 234, 0.05);
  border-radius: 12px;
  padding: 1.5rem;
  margin-top: 1rem;
}

.contact-info p {
  margin-bottom: 0.5rem;
}

.contact-info p:last-child {
  margin-bottom: 0;
}

@media (max-width: 768px) {
  .privacy-page {
    padding: 1rem;
  }
  
  .page-header h1 {
    font-size: 2rem;
  }
  
  .content-container {
    padding: 2rem;
  }
  
  .policy-section h2 {
    font-size: 1.3rem;
  }
  
  .policy-section h3 {
    font-size: 1.1rem;
  }
}
</style>

// src/app/[locale]/privacy/page.tsx

import type { Metadata } from "next";
import { Link } from "@/i18n/navigation";
import ScrollReveal from "@/components/ScrollReveal";
import JsonLd from "@/components/JsonLd";
import { getBreadcrumbSchema } from "@/lib/structured-data";
import { translate } from "@/lib/i18n";
import { getServerLocale } from "@/lib/server-locale";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "How Cloudless.gr collects, uses, and protects your personal data. GDPR and CCPA compliant.",
};

/* ── Section helper ──────────────────────────────────────── */

function Section({
  id,
  title,
  children,
}: {
  id: string;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section id={id} className="scroll-mt-24">
      <h2 className="text-neon-cyan/80 font-heading mb-4 text-xl font-bold text-white">{title}</h2>
      <div className="space-y-3 text-sm leading-relaxed text-slate-300">{children}</div>
    </section>
  );
}

/* ── Page ─────────────────────────────────────────────────── */

export default async function PrivacyPolicyPage() {
  const locale = await getServerLocale();
  const t = (key: string, fallback: string) => translate(locale, key, fallback);

  return (
    <>
      <JsonLd
        data={getBreadcrumbSchema([
          { name: "Home", url: "https://cloudless.gr" },
          { name: "Privacy Policy", url: "https://cloudless.gr/privacy" },
        ])}
      />

      <div className="bg-void min-h-screen">
        <div className="mx-auto max-w-3xl px-6 py-20 lg:py-28">
          <ScrollReveal>
            <p className="text-neon-cyan/70 mb-4 font-mono text-xs tracking-widest">
              {t("legal.legalDocument", "LEGAL DOCUMENT")}
            </p>
            <h1 className="font-heading mb-4 text-3xl font-bold text-white lg:text-4xl">
              {t("legal.privacyTitle", "Privacy Policy")}
            </h1>
            <p className="mb-2 font-mono text-xs text-slate-500">
              {t("legal.lastUpdated", "Last updated")}: April 2026
            </p>
            <p className="mb-12 text-sm leading-relaxed text-slate-400">
              {t(
                "legal.privacyIntro",
                'This Privacy Policy explains how Cloudless ("we", "us", "our") collects, uses, discloses, and safeguards your information when you visit cloudless.gr and use our services. We are committed to protecting your privacy in compliance with the EU General Data Protection Regulation (GDPR), the ePrivacy Directive, and the California Consumer Privacy Act (CCPA/CPRA).'
              )}
            </p>
          </ScrollReveal>

          <div className="space-y-10">
            <ScrollReveal>
              <Section id="controller" title={t("legal.controllerTitle", "1. Data Controller")}>
                <p>
                  {t(
                    "legal.controllerText",
                    "The data controller responsible for your personal data is Cloudless, operated by Themistoklis Baltzakis, based in Greece, EU. For data protection inquiries, contact us at:"
                  )}
                </p>
                <p className="font-mono text-xs">
                  {t("legal.controllerEmail", "Email: tbaltzakis@cloudless.gr")}
                </p>
              </Section>
            </ScrollReveal>

            <ScrollReveal>
              <Section
                id="data-collected"
                title={t("legal.dataCollectedTitle", "2. Information We Collect")}
              >
                <p className="font-semibold text-white">
                  {t("legal.dataProvidedTitle", "Information you provide directly:")}
                </p>
                <p>
                  {t(
                    "legal.dataProvided",
                    "Name, email address, company name, and message content when you submit our contact form. Email address when you subscribe to our newsletter. Account credentials when you register. Payment information when you purchase products or services (processed by Stripe — we never store card details)."
                  )}
                </p>
                <p className="font-semibold text-white">
                  {t("legal.dataAutoTitle", "Information collected automatically:")}
                </p>
                <p>
                  {t(
                    "legal.dataAuto",
                    "IP address (anonymised for analytics), browser type and version, device type, operating system, pages visited, time spent on pages, referring URL. This data is only collected if you consent to analytics cookies."
                  )}
                </p>
              </Section>
            </ScrollReveal>

            <ScrollReveal>
              <Section
                id="legal-basis"
                title={t("legal.legalBasisTitle", "3. Legal Basis for Processing (GDPR)")}
              >
                <p>
                  {t(
                    "legal.legalBasis",
                    "We process your personal data on the following legal bases: (a) Consent — for newsletter subscriptions, analytics cookies, and marketing cookies. You may withdraw consent at any time. (b) Contract performance — to fulfil orders and deliver services you have purchased. (c) Legitimate interest — for fraud prevention, security, and improving our services. (d) Legal obligation — for tax and accounting records required by Greek and EU law."
                  )}
                </p>
              </Section>
            </ScrollReveal>

            <ScrollReveal>
              <Section id="cookies" title={t("legal.cookiesTitle", "4. Cookies & Tracking")}>
                <p>
                  {t(
                    "legal.cookiesText",
                    "We use cookies in three categories: (1) Necessary cookies — required for the site to function (session management, consent preferences, security). These cannot be disabled. (2) Analytics cookies — help us understand how visitors use the site. Only set with your consent. (3) Marketing cookies — used for targeted advertising. Only set with your consent. You can manage your preferences at any time via the cookie settings link in our footer, or in your browser settings."
                  )}
                </p>
                <p>
                  <Link href="/cookies" className="text-neon-cyan hover:underline">
                    {t("legal.fullCookiePolicy", "Read our full Cookie Policy")}
                  </Link>
                </p>
              </Section>
            </ScrollReveal>

            <ScrollReveal>
              <Section id="data-use" title={t("legal.dataUseTitle", "5. How We Use Your Data")}>
                <p>
                  {t(
                    "legal.dataUse",
                    "We use your data to: respond to your contact form enquiries, process and fulfil orders, send newsletter updates (only with consent), improve our website and services, comply with legal obligations, prevent fraud and ensure security, and — with consent — personalise content and advertising."
                  )}
                </p>
              </Section>
            </ScrollReveal>

            <ScrollReveal>
              <Section
                id="data-sharing"
                title={t("legal.dataSharingTitle", "6. Data Sharing & Third Parties")}
              >
                <p>
                  {t(
                    "legal.dataSharing",
                    "We share data only with processors that are necessary to deliver our services: Stripe (payment processing, US — EU-US Data Privacy Framework certified), and Amazon Web Services (hosting, email via SES, and authentication via Amazon Cognito — EU region). We do not sell your personal data. Each third-party processor is bound by a Data Processing Agreement (DPA) and processes data only on our instructions."
                  )}
                </p>
              </Section>
            </ScrollReveal>

            <ScrollReveal>
              <Section
                id="data-transfers"
                title={t("legal.dataTransfersTitle", "7. International Data Transfers")}
              >
                <p>
                  {t(
                    "legal.dataTransfers",
                    "Some of our processors (e.g. Stripe) are based in the United States. These transfers are protected by the EU-US Data Privacy Framework, Standard Contractual Clauses (SCCs), or your explicit consent, in accordance with GDPR Chapter V."
                  )}
                </p>
              </Section>
            </ScrollReveal>

            <ScrollReveal>
              <Section id="retention" title={t("legal.retentionTitle", "8. Data Retention")}>
                <p>
                  {t(
                    "legal.retention",
                    "Contact form submissions: 2 years, then deleted. Newsletter subscriptions: until you unsubscribe. Purchase records: 7 years (Greek tax law requirement). Account data: until you request deletion. Analytics data: 14 months (anonymised). Cookie consent records: 1 year."
                  )}
                </p>
              </Section>
            </ScrollReveal>

            <ScrollReveal>
              <Section id="your-rights" title={t("legal.yourRightsTitle", "9. Your Rights")}>
                <p className="font-semibold text-white">
                  {t("legal.gdprRightsTitle", "Under the GDPR, you have the right to:")}
                </p>
                <p>
                  {t(
                    "legal.gdprRights",
                    'Access — request a copy of your personal data. Rectification — correct inaccurate data. Erasure — request deletion of your data ("right to be forgotten"). Restriction — limit how we process your data. Portability — receive your data in a machine-readable format. Objection — object to processing based on legitimate interest. Withdraw consent — at any time, without affecting prior processing.'
                  )}
                </p>
                <p className="font-semibold text-white">
                  {t("legal.ccpaRightsTitle", "Under the CCPA/CPRA (California residents):")}
                </p>
                <p>
                  {t(
                    "legal.ccpaRights",
                    "Right to know what personal data we collect and why. Right to delete your personal data. Right to opt out of the sale of personal data (we do not sell your data). Right to non-discrimination for exercising your privacy rights."
                  )}
                </p>
                <p>
                  {t(
                    "legal.rightsExercise",
                    "To exercise any of these rights, email us at tbaltzakis@cloudless.gr. We will respond within 30 days (GDPR) or 45 days (CCPA)."
                  )}
                </p>
              </Section>
            </ScrollReveal>

            <ScrollReveal>
              <Section id="children" title={t("legal.childrenTitle", "10. Children's Privacy")}>
                <p>
                  {t(
                    "legal.children",
                    "Our services are not directed at children under 16. We do not knowingly collect personal data from children. If you believe we have inadvertently collected such data, please contact us immediately."
                  )}
                </p>
              </Section>
            </ScrollReveal>

            <ScrollReveal>
              <Section id="security" title={t("legal.securityTitle", "11. Data Security")}>
                <p>
                  {t(
                    "legal.security",
                    "We implement appropriate technical and organisational measures to protect your data, including: HTTPS/TLS encryption in transit, encryption at rest for stored data, access controls and authentication, regular security reviews, and incident response procedures."
                  )}
                </p>
              </Section>
            </ScrollReveal>

            <ScrollReveal>
              <Section id="complaints" title={t("legal.complaintsTitle", "12. Complaints")}>
                <p>
                  {t(
                    "legal.complaints",
                    "If you believe we have not handled your data correctly, you have the right to lodge a complaint with the Hellenic Data Protection Authority (HDPA) at www.dpa.gr, or your local supervisory authority if you reside in another EU/EEA country."
                  )}
                </p>
              </Section>
            </ScrollReveal>

            <ScrollReveal>
              <Section id="changes" title={t("legal.changesTitle", "13. Changes to This Policy")}>
                <p>
                  {t(
                    "legal.changes",
                    'We may update this Privacy Policy from time to time. Material changes will be communicated via a notice on our website. The "Last updated" date at the top reflects the most recent revision.'
                  )}
                </p>
              </Section>
            </ScrollReveal>
          </div>
        </div>
      </div>
    </>
  );
}
